version: '3.8'

services:
  auth-service:
    build:
      context: .
      target: development
    container_name: marketwars-auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - marketwars-network
    depends_on:
      - redis

  # Redis for JWT token storage
  redis:
    image: redis:7-alpine
    container_name: marketwars-redis
    ports:
      - "6379:6379"
    networks:
      - marketwars-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Production service
  auth-service-prod:
    build:
      context: .
      target: production
    container_name: marketwars-auth-service-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - marketwars-network
    profiles:
      - production
    depends_on:
      - redis

networks:
  marketwars-network:
    driver: bridge
